#ifndef	H_MSDOS
#define	H_MSDOS
/****************************************************************************\
* 																			 *
* Template:		<^f^>														 *
* 																			 *
* File:		msdos.h															 *
* 																			 *
* Description:	Things required to make this work with MS-Dos.				 *
* 																			 *
* Created by:	Bruce A. Mallett	22-Mar-1989								 *
* 																			 *
*             Copyright (C) 1988  Bruce A. Mallett dba M-Tek				 *
*                          All rights reserved								 *
* 																			 *
\****************************************************************************/

/****************************************************************************\
* 																			 *
* MAXPATHLEN																 *
* 	This defines the maximum number of characters allowed in a path string.	 *
* 																			 *
\****************************************************************************/

#define	MAXPATHLEN			256

#endif									/* H_MSDOS */
